cat("Welcome to the 2024 IOTC Yellowfin assessment project.\n")
require(dplyr)
require(purrr)
require(readr)
require(sf)
require(stringr)
library(reshape)
library(r4ss)
library(readxl)
library(scales)
library(tidyr)
library(FishFreqTree)